theme: jekyll-theme-cayman

google_analytics: UA-128972978-1

title: "CKC Blog"
description: "WE ♡ DEVELOPMENT! Specializing with Python + Django in CDA, Idaho -- We help startups and growing businesses create, improve, or fix their apps — you come to us with the problem and we’ll find ways to solve it"

plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"
excerpt_separator: <!--more-->

collections:
  authors:
    output: true

#defaults:
#  - scope:
#      path: ""
#      type: "authors"
#    values:
#      layout: "author"
#  - scope:
#      path: ""
#      type: "posts"
#    values:
#      layout: "post"
#  - scope:
#      path: ""
#    values:
#      layout: "default"
