theme: jekyll-theme-cayman

google_analytics: UA-128972978-1

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect
  - jekyll-seo-tag
  - jekyll-minifier
  - jerkyl-brotli

paginate: 5
paginate_path: "/blog/page:num/"
excerpt_separator: <!--more-->

collections:
  authors:
    output: true

whitelist:
  - jekyll-redirect-from


# SEO

title: "CKC - Web Dev Shop in Coeur d'Alene (CDA) Idaho"
tagline: "We help businesses create and design their app, website, business tools."
description: "Need Software? We're rockstar software developers: django, python, vue, react. Web and mobile. Spokane Coeur d'Alene area."

twitter:
  card: summary_large_image
  username: CKCollab


social:
  name: CK Collab
  links:
    - https://www.facebook.com/ckcollab/
    - https://twitter.com/ckcollab/
    - https://www.linkedin.com/company/33456525/
    - https://github.com/orgs/ckc-org/
    - https://clutch.co/profile/ckc


#defaults:
#  - scope:
#      path: ""
#      type: "authors"
#    values:
#      layout: "author"
#  - scope:
#      path: ""
#      type: "posts"
#    values:
#      layout: "post"
#  - scope:
#      path: ""
#    values:
#      layout: "default"
